-- Junção entre tabelas com o JOIN
SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, COUNT(*) AS NUMERO_NOTAS FROM NOTAS_FISCAIS GROUP BY MATRICULA;

SELECT NF.MATRICULA, V.NOME, COUNT(*) AS NUMERO_NOTAS 
FROM TABELA_DE_VENDEDORES V
INNER JOIN NOTAS_FISCAIS NF
ON NF.MATRICULA = V.MATRICULA
GROUP BY NF.MATRICULA, V.NOME;