-- Praticando o uso do LEFT, RIGHT E FULL JOIN
SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- 16 Clientes -> 7 Clientes possuem vendedores nos seus bairros

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
-- 4 Vendedores -> 3 Vendedores possuem clientes nos seus bairros

SELECT DISTINCT
    TV.NOME AS NOME_DO_VENDEDOR,
    TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
    TC.BAIRRO AS BAIRRO_DO_CLIENTE
    TC.NOME AS NOME_DO_CLIENTE,
FROM 
TABELA_DE_CLIENTES TC
INNER JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO

-- Qual é o vendedor que não tem cliente no seu bairro? -> ROBERTA MARTINS EM COPACABANA
SELECT DISTINCT
    TV.NOME AS NOME_DO_VENDEDOR,
    TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
    TC.BAIRRO AS BAIRRO_DO_CLIENTE
    TC.NOME AS NOME_DO_CLIENTE,
FROM 
TABELA_DE_CLIENTES TC
RIGHT JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.NOME IS NULL

-- Quais clientes moram em bairros que não possuem vendedores? -> 9 CLIENTES
SELECT DISTINCT
    TV.NOME AS NOME_DO_VENDEDOR,
    TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
    TC.BAIRRO AS BAIRRO_DO_CLIENTE
    TC.NOME AS NOME_DO_CLIENTE,
FROM 
TABELA_DE_CLIENTES TC
LEFT JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TV.NOME IS NULL

-- RESPONDENDO AS 2 PERGUNTAS NUMA ÚNICA QUERY
SELECT DISTINCT
    TV.NOME AS NOME_DO_VENDEDOR,
    TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
    TC.BAIRRO AS BAIRRO_DO_CLIENTE
    TC.NOME AS NOME_DO_CLIENTE,
FROM 
TABELA_DE_CLIENTES TC
FULL JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO