-- Union e Union ALL
SELECT 
    CLIENTE,
    CIDADE,
    ESTADO
FROM CLIENTE
UNION
SELECT
    FORNECEDOR,
    CIDADE,
    ESTADO
FROM FORNECEDOR

-- UNION APLICA POR SI SÓ O DISTINCT PARA NAO EXIBIR REPETIDAS

-- UNION ALL REPETE OS ITENS IGUAIS (SEM O DISTINCT)
SELECT
    CIDADE,
    ESTADO
FROM CLIENTE
UNION ALL
SELECT
    CIDADE,
    ESTADO
FROM FORNECEDOR

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
-- 12 BAIRROS -> CLIENTES

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
-- 4 BAIRROS -> VENDEDORES

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
-- 13 BAIRROS

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
-- 16 BAIRROS

SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;
-- 16 BAIRROS COM NOMES DISTINTOS PELA ORIGEM DO DADO