-- Distinguindo dados repetidos da consulta - DISTINCT
SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca';

SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS;