-- Maneiras diferentes de SELECT da tabela usando Apelidos (AS)
SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT NOME, CPF, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DO CLIENTE], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT TDC.CPF AS IDENTIFICADOR, TDC.NOME AS [NOME DO CLIENTE], TDC.BAIRRO, TDC.CIDADE FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

SELECT TABELA_DE_CLIENTES.CPF, TABELA_DE_CLIENTES.NOME FROM TABELA_DE_CLIENTES;